# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Nexys-A7-100T-Master.xdc

# IP: ip/mmcm/mmcm.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmcm || ORIG_REF_NAME==mmcm} -quiet] -quiet
